version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Dependencies
      - apt-get update 
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - sudo apt install nodejs
      - REPOSITORY_URI=${repository_url}
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - npm install && npm run migrate:latest
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"${cluster_name}-${environment}-node-api","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
