version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      - echo Installing Dependencies
  pre_build:
    commands:
      - apt-get update 
      - REPOSITORY_URI=${repository_url}
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"${cluster_name}-${environment}-node-api","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes